// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuK2VB18SED5t94WfUkHwyKk9mkBWKaDg',
    appId: '1:651130356443:web:e305899614ceb29d14c2fe',
    messagingSenderId: '651130356443',
    projectId: 'queueflow-af838',
    authDomain: 'queueflow-af838.firebaseapp.com',
    storageBucket: 'queueflow-af838.firebasestorage.app',
    measurementId: 'G-W7NHKX5MVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdvybIVsmwrWf0V1fDf3ghvR3xHbGnG8c',
    appId: '1:651130356443:android:af76faff8535d9d114c2fe',
    messagingSenderId: '651130356443',
    projectId: 'queueflow-af838',
    storageBucket: 'queueflow-af838.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCib0-Ds-pXAAskgI2kUw637qZTtYbU5pI',
    appId: '1:651130356443:ios:3a73d56760d0677614c2fe',
    messagingSenderId: '651130356443',
    projectId: 'queueflow-af838',
    storageBucket: 'queueflow-af838.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCib0-Ds-pXAAskgI2kUw637qZTtYbU5pI',
    appId: '1:651130356443:ios:3a73d56760d0677614c2fe',
    messagingSenderId: '651130356443',
    projectId: 'queueflow-af838',
    storageBucket: 'queueflow-af838.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg-3g2scwUfYWZV8JavWi9liVtnZX5MMY',
    appId: '1:651130356443:web:f85bb6937a8c23f514c2fe',
    messagingSenderId: '651130356443',
    projectId: 'queueflow-af838',
    authDomain: 'queueflow-af838.firebaseapp.com',
    storageBucket: 'queueflow-af838.firebasestorage.app',
    measurementId: 'G-DF4MNGXPDR',
  );
}